'use strict';

function r(o) {
  o.createdAt = new Date();
  o.updatedAt = new Date();
  return o;
}

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Stories', [
      r({userId: 1, genreId: 1, title: 'GOT: Alt Ending', synopsis: `We do it together," Daenerys urged. "We break the wheel together."

      Jon had come to speak with her, to hear Daenerys defend her actions with her own words, but all she did was spout Targeryen madness. Conquer the entire world, a never-ending war, and herself above all others as the ultimate judge of right and wrong, willing to murder thousands.

      He remembered the words of the man who would always be his father. The most honorable man he'd ever known. "The man who passes the sentence should swing the sword. If you would take a man's life, you owe it to him to look into his eyes and hear his final words. And if you cannot bear to do that, then perhaps the man does not deserve to die."

      He'd been fighting against what he had to do, but now he was certain. As they embraced he plunged his dagger into the heart of the Mad Queen. Death came swiftly she didn't even have any final words as the shock and betrayal in her eyes faded with her life. He lowered her gently to the floor as Drogon roared.

      He'd know the great beast was smart, even smarter than Ghost, but this was magic. It knew. Somehow it knew and it was coming from him. He backed away from winged death as it landed, but instead it went to Daenerys and nuzzled her like a hound at its dead master. She'd called herself Mother of Dragons, and he knew the stories, but only now did he realize the full truth of them. Drogon mourned what was his mother in every way.

      Jon dodged quickly as Drogon reared to breathe flame. He'd expected to feel the flames but instead the beast aimed at the throne. The damned throne that Daenerys had been telling stories about just minutes before. As the beast gently scooped up the Mother of Dragons and flew away, Jon realized that he'd still underestimated the creature's intelligence.

      "You know nothing, Jon Snow," played once again in his mind. Ygritte. He should have stayed in that cave with her. He'd as good as killed her. Now his only other lover was dead at his own hand. Duty is the death of love. He should have loved Daenerys. That's all she'd asked of him. If he hadn't rejected her, if he hadn't left her alone and isolated when all closest to her turned their backs on her, would this have happened?

      He still knew nothing. Sansa wanted him for the throne, as did Tyrion, but they would name him Queenslayer. He had become Jamie Lannister. What was left for him? He walked to the ledge where a dwindling speck in the sky was all that could be seen of the last dragon. Hundreds of feet below him lay the broken ruins of King's Landing

      He stepped forward.`, rating: 28, read: false, confirmedPostLength: 17}),
      r({userId: 1, genreId: 5, title: 'A Tale of Some Cities', synopsis: `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 46, read: false, confirmedPostLength: 9}),
      r({userId: 4, genreId: 7, title: 'Bobenstein', synopsis:  `I am by birth a Genevese, and my family is one of the most distinguished of that republic. My ancestors had been for many years counsellors and syndics, and my father had filled several public situations with honour and reputation. He was respected by all who knew him for his integrity and indefatigable attention to public business. He passed his younger days perpetually occupied by the affairs of his country; a variety of circumstances had prevented his marrying early, nor was it until the decline of life that he became a husband and the father of a family. `, rating: 72, read: false, confirmedPostLength: 19}),
      r({userId: 2, genreId: 3, title: 'Plant People', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: -15, read: false, confirmedPostLength: 6}),
      r({userId: 6, genreId: 2, title: 'Alien Musk', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 26, read: false, confirmedPostLength: 5}),
      r({userId: 5, genreId: 6, title: 'Once and Unremembered', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 10, read: false, confirmedPostLength: 5}),
      r({userId: 2, genreId: 4, title: 'Redemption and Other Chores', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: -5, read: false, confirmedPostLength: 5}),
      r({userId: 4, genreId: 2, title: 'Fatal', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 120, read: false, confirmedPostLength: 5}),
      r({userId: 3, genreId: 5, title: 'Yeah-no-Yes!', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 59, read: false, confirmedPostLength: 5}),
      r({userId: 3, genreId: 7, title: 'Silent Room, Thunderous Night', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 5, read: false, confirmedPostLength: 5}),
      r({userId: 2, genreId: 7, title: 'The Lodger', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: -12, read: false, confirmedPostLength: 5}),
      r({userId: 5, genreId: 4, title: 'Ceremony Attendance', synopsis:  `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.`, rating: 62, read: false, confirmedPostLength: 5})
    ], {})
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Stories', null, {});
  }
};
